name: Continuous Integration

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Linter
        run: >
          DOCKER_BUILDKIT=1 docker build
          --target=linter
          --progress=plain
          .
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: >
          DOCKER_BUILDKIT=1 docker build
          --target=test
          --build-arg SDK_INTEGRATION_TESTS_SERVER_API_URL=${{ secrets.SDK_INTEGRATION_TESTS_SERVER_API_URL }}
          --build-arg SDK_INTEGRATION_TESTS_SERVER_KEY_ID=${{ secrets.SDK_INTEGRATION_TESTS_SERVER_KEY_ID }}
          --build-arg SDK_INTEGRATION_TESTS_SERVER_KEY_SECRET=${{ secrets.SDK_INTEGRATION_TESTS_SERVER_KEY_SECRET }}
          .
