name: Continuous Integration

on: pull_request

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Linter
        run: docker build --target linter .
